### PR TITLE
refactor: Add bot version stamp to image embeds

### LINKED ISSUE #118: Add bot version stamp to image embeds
Desired output:
`jlyons210/discord-bot-ol-bootsie v1.1.0` or `jlyons210/discord-bot-ol-bootsie (1.1.0)` - whichever ends up looking better.

Code location:
[DiscordBot.ts#L500](https://github.com/jlyons210/discord-bot-ol-bootsie/blob/afb4b839cdaba1b0f43025a3abc61c4b4fcd99d7/src/lib/DiscordBot/DiscordBot.ts#L500)

### PR DESCRIPTION
**Pull request by divyakelaskar**
### 🛠️ Fixes Issue

Closes #118 

### 👨‍💻 Changes proposed

Add bot version stamp to image embeds

### ✔️ Check List

- [x] renamed to `jlyons210/discord-bot-ol-bootsie v1.1.0`.

### CODE REVIEW

**Comment by jlyons210** [comment]
Hello - thank you for your contribution! Ideally this would not be hard-coded, and instead use `process.env['npm_package_version']`. Would you like to modify and commit an update?

**Comment by divyakelaskar** [comment]
Yes, I would like to know the process to add `process.env['npm_package_version']`

**Comment by jlyons210** [comment]
Great! So you can see an example of where that is being used [here](https://github.com/jlyons210/discord-bot-ol-bootsie/blob/afb4b839cdaba1b0f43025a3abc61c4b4fcd99d7/src/app.ts#L26). You'll notice that instead of single-quotes - ' - around the string, backticks - `` - are being used, and the variable is being plugged in using `${variable_name}`.

This is called [string interpolation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#string_interpolation).

**Comment by jlyons210** [comment]
Your [most recent commit](https://github.com/jlyons210/discord-bot-ol-bootsie/pull/119/commits/74646781d12422f5dafb603c071ce895322eabcd) is very close! The GitHub URL was removed though.

Line 500 should read:
```typescript
          text: `jlyons210/discord-bot-ol-bootsie ${npmPackageVersion}`,
```

I see that you set the value for `npmPackageVersion` correctly on line 61, so this last change could be merged. Thank you! 🙌

**Review by jlyons210 — APPROVED** [review]
LGTM

**Comment by jlyons210** [comment]
Thank you for your contribution @divyakelaskar 🙌

**Pull request merged**
